FROM docker.elastic.co/beats/filebeat:5.5.0
# RUN chmod go-w /usr/share/filebeat/filebeat.yml
# COPY filebeat.yml /usr/share/filebeat/filebeat.yml
# USER root
# RUN chown filebeat /usr/share/filebeat/filebeat.yml
USER filebeat