filebeat.prospectors:
- input_type: log
  paths:
    - /mnt/log/*.log
    - /mnt/celog/*.log
  fields:
    ip_from: '${local_host}'

processors:
- add_cloud_metadata:

# output.logstash:
#   hosts: [ "logstash:5044" ]
output.redis:
  hosts: [ "${elk_host}:6379" ]
  key: "filebeat"
  db: 0
  timeout: 5