version: '2'
services:
  db:
    image: postgres
  redis:
    image: "redis:alpine"
  celery:
    build: .
    privileged: true
    command: "/home/dqa/code/env/bin/celery -A pressure_test worker -l info -f %n-%i.log"
    volumes:
      - .:/home/dqa/data
    links:
      - db
      - redis
  web:
    build: .
    privileged: true
    entrypoint: /home/dqa/data/entrypoint.sh
    volumes:
      - .:/home/dqa/data
    depends_on:
      - db
    links:
      - redis
  sut:
    build: .
    privileged: true
    entrypoint: /home/dqa/data/test.sh
    volumes:
      - .:/home/dqa/data
    depends_on:
      - db
    links:
      - redis
      - web