version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    entrypoint: /home/dqa/data/entrypoint.sh
    volumes:
      - .:/home/dqa/data
    ports:
      - "8000:8000"
    depends_on:
      - db