version: '3'
services:
  web:
    privileged: true
    entrypoint: /home/dqa/data/entrypoint.test.sh
    volumes:
      - .:/home/dqa/data
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=${NODE_ENV}