version: '3'
services:
  db:
    image: postgres
  redis:
    image: "redis:alpine"
  celery:
    build: .
  web:
    build: .
    depends_on:
      - db
    links:
      - redis
  filebeat:
    build: filebeat